---
# tasks file for instalacja
- name: check VTMS version
  get_url:
    url: '{{ repo_location }}/{{ descriptor_filename }}'
    validate_certs: false
    dest: /tmp/vtms.xml

- name: get VTMS version
  uri:
    url: '{{ repo_location }}/{{ descriptor_filename }}'
    method: GET
    content_as_json: true
    validate_certs: no
    return_content: yes
    register: vtms_version

    #- debug:
      #var: vtms_version.content
      #
- name: get URL from XML
  shell: sed -n 's:.*<url>\(.*\)</url>.*:\1:p' < /tmp/vtms.xml
  register: vtms_url

- name: get deployment file
  get_url:
    url: '{{ vtms_url }}'
    #url: https://alpha.novelpay.pl/tmsc\CS_TEST.xml
    #status_code: 200
    validate_certs: false
    dest: /tmp/

